# Docker Compose file for Nx Assurance Code React/Angular Monorepo
#
# This file defines the services, networks, and volumes for running React-App and Angular-App
# in a containerized environment. There is also a base service for shared dependencies.
#
# Execution:
#   docker-compose up --build
#
# Services:
#   - base_service: Installs and shares node_modules for all apps
#   - react-app: Runs the React application (port 3000)
#   - angular-app: Runs the Angular application (port 4200)
# 
# version: '3.8'

services:
  base_service:
  # Base service to install dependencies and share node_modules
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./base_service:/apps
      - base_service_node_modules:/apps/node_modules
  react-app:
    build:
  # React app  service
      context: .
      dockerfile: apps/react-app/Dockerfile
    volumes:
      - base_service_node_modules:/apps/node_modules
    container_name: nx-react-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - nx-network

  angular-app:
    build:
  # Angular app service
      context: .
      dockerfile: apps/angular-app/Dockerfile
    volumes:
      - base_service_node_modules:/apps/node_modules
    container_name: nx-angular-app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - nx-network

networks:
  nx-network:
    driver: bridge
  # Custom bridge network for inter-service communication

volumes:
  base_service_node_modules:

  # A shared volume for node_modules to avoid re-installing dependencies in each container
