# version: '3.8'

services:
  base_service:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./base_service:/apps
      - base_service_node_modules:/apps/node_modules
  react-app:
    build:
      context: .
      dockerfile: apps/react-app/Dockerfile
    volumes:
      - base_service_node_modules:/apps/node_modules
    container_name: nx-react-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - nx-network

  angular-app:
    build:
      context: .
      dockerfile: apps/angular-app/Dockerfile
    volumes:
      - base_service_node_modules:/apps/node_modules
    container_name: nx-angular-app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - nx-network

networks:
  nx-network:
    driver: bridge

volumes:
  base_service_node_modules:
